### PR TITLE
Use link from config file instead of hardcoded

### PR DESCRIPTION
**Pull request by DavidNgugi**
This is in reference to issue #27

### CODE REVIEW

**Comment by Skowt** [comment]
Just noticed this and it looks like the PR doesn't update the ServiceProvider route config:
https://github.com/larsjanssen6/underconstruction/blob/master/src/UnderConstructionServiceProvider.php#L47

Heads up but nice one @DavidNgugi

**Comment by larsjanssen6** [comment]
@DavidNgugi thanks for your pr. Could you add it in the serviceprovider aswel? See reaction from @Skowt above. Thanks!

**Comment by DavidNgugi** [comment]
Ok. I'll check it out

**Comment by DavidNgugi** [comment]
@larsjanssen6 and  @Skowt I think the issue was with the commit [https://github.com/larsjanssen6/underconstruction/pull/32/commits/97831d047f28e3b94d2174776ea282b6044ca374](url) which I fixed with a consecutive commit [https://github.com/larsjanssen6/underconstruction/pull/32/commits/be9538595569e336b1ab6f7347b449f19264a443](url)

**Pull request merged**
