### PR TITLE
Modified to accept custom route prefix and custom endpoint

### PR DESCRIPTION
**Pull request by Owen-oj**
I modified this package to accept custom route prefix and custom endpoint.  For example, if you want the default page to use `auth/checkpoint`, you can just add these to your .env file 

```
UNDER_CONSTRUCTION_ROUTE_PREFIX = 'auth'  
UNDER_CONSTRUCTION_CUSTOM_ENDPOINT = 'checkpoint'
```
**NB**: These modifications doesn't change the normal behavior of the package.

Annotation 2019-10-28 211746

### CODE REVIEW

**Comment by larsjanssen6** [comment]
@Owen-oj Thx!

**Comment by Owen-oj** [comment]
@larsjanssen6 please will this be merged soon?

**Comment by larsjanssen6** [comment]
@Owen-oj whoops sorry will check in a couple of days.

**Comment by larsjanssen6** [comment]
@Owen-oj here you go https://github.com/larsjanssen6/underconstruction/releases/tag/5.1 👍

**Pull request merged**
